#Main actionbars in the server
titleraw @a[scores={depa=0},tag=!Adminer] actionbar {"rawtext":[{"text":" §6    "},{"selector":"*"},{"text":"\n    §6§o§eKills: §f"},{"score":{"name":"*","objective":"kill"}},{"text":"  Skill: §b"},{"score":{"name":"*","objective":"Dones"}},{"text":"   §cDeath: §f"},{"score":{"name":"*","objective":"_Death"}}]}
titleraw @a[scores={depa=1..,kill=0..},tag=!Adminer] actionbar {"rawtext":[{"text":" §6    "},{"selector":"*"},{"text":"    §6§o§eKills: §f"},{"score":{"name":"*","objective":"kill"}},{"text":"  Skill: §b"},{"score":{"name":"*","objective":"Dones"}},{"text":"\n §d"},{"score":{"name":"*","objective":"_9999"}},{"text":"   §3Home §b"},{"score":{"name":"*","objective":"depa"}},{"text":"   §cDeaths: §f"},{"score":{"name":"*","objective":"_Death"}}]}
#titleraw @a[scores={kill=100..199},tag=!Adminer,tag=!Helpa] actionbar {"rawtext":[{"text":" §6      "},{"selector":"*"},{"text":"    §6§o§eKills: §f"},{"score":{"name":"*","objective":"kill"}},{"text":"  Skill: §b"},{"score":{"name":"*","objective":"Dones"}},{"text":"\n §dBalance: §5$"},{"score":{"name":"*","objective":"_9999"}},{"text":"   §3Home §b"},{"score":{"name":"*","objective":"depa"}},{"text":"   §cDeaths: §f"},{"score":{"name":"*","objective":"_Death"}},{"text":"   §aStatus: §6Hunter I§r"}]}
#titleraw @a[scores={kill=200..399},tag=!Adminer,tag=!Helpa] actionbar {"rawtext":[{"text":" §6      "},{"selector":"*"},{"text":"    §6§o§eKills: §f"},{"score":{"name":"*","objective":"kill"}},{"text":"  Skill: §b"},{"score":{"name":"*","objective":"Dones"}},{"text":"\n §dBalance: §5$"},{"score":{"name":"*","objective":"_9999"}},{"text":"   §3Home §b"},{"score":{"name":"*","objective":"depa"}},{"text":"   §cDeaths: §f"},{"score":{"name":"*","objective":"_Death"}},{"text":"   §aStatus: §6Hunter II§r"}]}
#titleraw @a[scores={kill=400..799},tag=!Adminer,tag=!Helpa] actionbar {"rawtext":[{"text":" §6      "},{"selector":"*"},{"text":"    §6§o§eKills: §f"},{"score":{"name":"*","objective":"kill"}},{"text":"  Skill: §b"},{"score":{"name":"*","objective":"Dones"}},{"text":"\n §dBalance: §5$"},{"score":{"name":"*","objective":"_9999"}},{"text":"   §3Home §b"},{"score":{"name":"*","objective":"depa"}},{"text":"   §cDeaths: §f"},{"score":{"name":"*","objective":"_Death"}},{"text":"   §aStatus: §6Hunter III§r"}]}
#titleraw @a[scores={kill=800..}] title {"rawtext":[{"text":" §6      "},{"selector":"*"},{"text":"    §6§o§eKills: §f"},{"score":{"name":"*","objective":"kill"}},{"text":"  Skill: §b"},{"score":{"name":"*","objective":"Dones"}},{"text":"\n §dBalance: §5$"},{"score":{"name":"*","objective":"_9999"}},{"text":"   §3Home §b"},{"score":{"name":"*","objective":"depa"}},{"text":"   §cDeaths: §f"},{"score":{"name":"*","objective":"_Death"}},{"text":"   §aStatus: §l§dElite§r"}]}
#titleraw @a[tag=Helpa,scores={kill=..799}] actionbar {"rawtext":[{"text":" §6      "},{"selector":"*"},{"text":"    §6§o§eKills: §f"},{"score":{"name":"*","objective":"kill"}},{"text":"  Skill: §b"},{"score":{"name":"*","objective":"Dones"}},{"text":"\n §dBalance: §5$"},{"score":{"name":"*","objective":"_9999"}},{"text":"   §3Home §b"},{"score":{"name":"*","objective":"depa"}},{"text":"   §cDeaths: §f"},{"score":{"name":"*","objective":"_Death"}},{"text":"   §aStatus: §6§lHelper§r"}]}
titleraw @a[tag=Adminer,scores={kill=0..}] actionbar {"rawtext":[{"text":" §6    "},{"selector":"*"},{"text":"    §6§o§eKills: §f"},{"score":{"name":"*","objective":"kill"}},{"text":"  Skill: §b"},{"score":{"name":"*","objective":"Dones"}},{"text":"\n §d"},{"score":{"name":"*","objective":"_9999"}},{"text":"   §3Home: §b"},{"score":{"name":"*","objective":"depa"}},{"text":"   §cDeaths: §f"},{"score":{"name":"*","objective":"_Death"}},{"text":" §3D: §f"},{"score":{"name":"*","objective":"time_10"}},{"text":"  "},{"score":{"name":"*","objective":"time_11"}},{"text":":"},{"score":{"name":"*","objective":"time_01"}},{"text":":"},{"score":{"name":"*","objective":"time_00"}}]}
