scoreboard players set @a[name=AntonyKlaric] depa 1
scoreboard players set @a[name="Anthony Towerks"] depa 1
scoreboard players set @a[name=TonyBlogs] depa 2
scoreboard players set @a[name="MiguelOrea88"] depa 3
scoreboard players set @a[name=Kteimporta007] depa 4
scoreboard players set @a[name=XxvalderoxX] depa 5
scoreboard players set @a[name=AngelDavidRF] depa 6
scoreboard players set @a[name=Kazuma2195346] depa 7
scoreboard players set @a[name=ELBRAYAN2705] depa 8
scoreboard players set @a[name=Mahoma1995] depa 9
scoreboard players set @a[name=Tommate53] depa 10
scoreboard players set @a[name=Anonymus503] depa 11
scoreboard players set @a[name=SAUL7794] depa 12
scoreboard players set @a[name=hectords968] depa 13
scoreboard players set @a[name=dmo7u7] depa 14
scoreboard players set @a[name=Deadluis2324] depa 15
scoreboard players set @a[name=LiftedGsdw] depa 16
scoreboard players set @a[name="LuffoGG"] depa 17
