tag @a[name=AntonyKlaric] add Adminer
tag @a[name="Anthony Towerks"] add Adminer
tag @a[tag=Adminer] add staffstatus
#clear @a[tag=Adminer]
#scoreboard players set @a[tag=Adminer] illegalitemsvl 0
#execute @a[tag=Adminer] ~ ~ ~ function op
#tag @a[tag=Adminer] remove isBanned
#tag @a[tag=Adminer] remove By:Paradox
#tag @a[tag=Adminer] remove 'Reason:Illegal Item A (command_block)'
#tag @a[tag=Adminer] remove illegalitemsA